### ISSUE TITLE
Neuro project build error

### ISSUE THREAD

**Issue by ParkHaeChan** [Cr33zz/Neuro_#1]
I tried to build this project in vs2017  with Cuda10.2 and cudnn 7.6.5

first build Neuro project to get Neuro.lib but it failed with "can't open mkl_core.lib".

So I checked source codes and set MKL_DISABLED.

but it still have link error 1181 : "can't open mkl_core.lib".

I deleted include and lib directory in project property with mkl things but it still same problem.

**Comment by Cr33zz** [comment]
Hi, I recently added partial Intel Math Kernel Library (MKL) support and forgot to update the prerequisites. You can download it free of charge from the web. Hope that helps.

**Comment by ParkHaeChan** [comment]
Thanks it worked.
Now I'm trying to run Examples but your dropbox dataset is not connected to link(404 error)
Could you re-upload them please?

**Comment by Cr33zz** [comment]
Awesome :) I've updated the link, hope it works now.
