### ISSUE TITLE
can't access www.dropbox.com for download examples data

### ISSUE THREAD

**Issue by jjqcat** [Cr33zz/Neuro_#3]
I can't access www.dropbox.com to download examples data, would you give me other link?

**Comment by Cr33zz** [comment]
try this one https://www.dropbox.com/s/1zccfhtx9zi52mf/neuro_examples_data.zip?dl=0

**Comment by jjqcat** [comment]
sorry, this site can't access in China

**Comment by Cr33zz** [comment]
I'm sorry to hear that but I don't have any FTP server available and it's ~400MB :( you can try downloading the datasets on your own, as thy are publicly available. Majority of the datasets is referenced in examples.
