### ISSUE TITLE
bug -__-

### ISSUE THREAD

**Issue by frowrik** [Cr33zz/Neuro_#4]
https://github.com/Cr33zz/Neuro_/blob/878e43634e1ad269dc1b094dd8452818110ae498/Neuro/src/Tensors/Tensor.cpp#L364
https://github.com/Cr33zz/Neuro_/blob/878e43634e1ad269dc1b094dd8452818110ae498/Neuro/src/Tensors/Tensor.cpp#L366

wrong copy size results in assertion in CopyDepthTo->CopyTo->https://github.com/Cr33zz/Neuro_/blob/878e43634e1ad269dc1b094dd8452818110ae498/Neuro/src/Tensors/Tensor.cpp#L2119

I fixed it on
if (depth> 1)...
 if (depth> 2)...

**Comment by Cr33zz** [comment]
Yes, good catch, thanks for pointing it out, I will fix is asap.

**Comment by Cr33zz** [comment]
Fixed :)
