### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by ghost** [Cr33zz/Neuro_#5]
It looks very cool but it require modification to compile on Linux do you think you will support Linux later? I tried a little you need to change __int64 to something (maybe int64_t?)  and the super:: is a Microsoft only keyword for C++, I am not sure how that works to port it.

**Comment by Cr33zz** [comment]
Hey, thanks :) There are quite a few other problems I suspect. In its current form, it requires CuDNN, MKL, and FreeImage libraries. I didn't check if there are Linux counterparts for them (FreeImage I had to compile myself from source). Ideally, the first two could be made optional. Anyway, it is quite a bit of work, and while I can make some adjustments for easier Linux support, I don't have time to port it :(

**Comment by darkSKULL-labs** [comment]
It looks really cool what you have done and I would like to see it used but I am not good at C++ at all and can't help to port it. I can wrap it to use with Lua though which is all my tools I use to convert C and C++ into Lua, Python and other modules.

**Comment by darkSKULL-labs** [comment]
I am just real pumped up right now kicking ass on programming codes but I like what you have got and think it  can be very useful I will try to compile on my old windows machine I think I still have Visual C++ on it.
